DSEG	SEGMENT
	char	DW	4 DUP(0)
	inta	DW	7 DUP(0)
	float	DW	1 DUP(0)
	TEMP	DW	9 DUP(0)
	CONST	DW	2,1,0,3,5,15,8
DSEG	ENDS
CSEG	SEGMENT
	ASSUME	CS:CSEG,DS:DSEG
COUT	PROC	NEAR
	MOV	SI,10
	MOV	CX,0
next1:	MOV	DX,0
	DIV	SI
	PUSH	DX
	INC	CX
	CMP	AX,0
	JNZ	next1
next2:	POP	DX
	ADD	DL,30H
	MOV	AH,02H
	INT	21H
	LOOP	next2
	RET
COUT	ENDP
start:	MOV	AX,DSEG
	MOV	DS,AX
	MOV	AX,CONST[0]
	MOV	char[8],AX
	MOV	AX,CONST[2]
	MOV	char[10],AX
	MOV	AX,CONST[4]
	MOV	char[12],AX
	MOV	AX,CONST[0]
	MOV	BX,CONST[4]
	ADD	AX,BX
	MOV	TEMP[0],AX
	MOV	AX,TEMP[0]
	CALL	COUT
	MOV	AX,CONST[4]
	MOV	BX,CONST[2]
	ADD	AX,BX
	MOV	TEMP[2],AX
	MOV	AX,TEMP[2]
	AND	AX,AX
	JZ	t0
	MOV	AX,CONST[10]
	MOV	BX,char[8]
	SUB	AX,BX
	MOV	char[12],AX
	MOV	AX,CONST[12]
	MOV	char[14],AX
	MOV	AX,CONST[12]
	MOV	char[16],AX
	MOV	AX,CONST[0]
	MOV	char[18],AX
t0:	MOV	AX,CONST[0]
	MOV	BX,char[10]
	MUL	BX
	MOV	TEMP[12],AX
	MOV	AX,char[8]
	MOV	BX,TEMP[12]
	SUB	AX,BX
	MOV	TEMP[14],AX
	MOV	AX,TEMP[14]
	AND	AX,AX
	JZ	t1
	MOV	AX,char[8]
	MOV	BX,char[10]
	ADD	AX,BX
	MOV	char[12],AX
	JMP	t0
t1:	MOV	AX,CONST[6]
	MOV	char[22],AX
CSEG	ENDS
	END	START
